### Data Profiling

#### Importing Libraries

In [1]:
import numpy as np
import pandas as pd
from pathlib import Path

#### 33 Borough Files

In [2]:
# Loading the 33 London Borough Housing Files

project_root = Path('.').resolve().parent
raw_dir = project_root /'data'/'raw'
borough_files = sorted(raw_dir.glob('*_link_*.csv'))
print(f'Found {len(borough_files)} borough files')
for fp in borough_files:
    print(' ', fp.name)

Found 33 borough files
  Barking_and_Dagenham_link_26122024.csv
  Barnet_link_26122024.csv
  Bexley_link_26122024.csv
  Brent_link_26122024.csv
  Bromley_link_26122024.csv
  Camden_link_26122024.csv
  City_of_London_link_26122024.csv
  Croydon_link_26122024.csv
  Ealing_link_26122024.csv
  Enfield_link_26122024.csv
  Greenwich_link_26122024.csv
  Hackney_link_26122024.csv
  Hammersmith_and_Fulham_link_26122024.csv
  Haringey_link_26122024.csv
  Harrow_link_26122024.csv
  Havering_link_26122024.csv
  Hillingdon_link_26122024.csv
  Hounslow_link_26122024.csv
  Islington_link_26122024.csv
  Kensington_and_Chelsea_link_26122024.csv
  Kingston_upon_Thames_link_26122024.csv
  Lambeth_link_26122024.csv
  Lewisham_link_26122024.csv
  Merton_link_26122024.csv
  Newham_link_26122024.csv
  Redbridge_link_26122024.csv
  Richmond_upon_Thames_link_26122024.csv
  Southwark_link_26122024.csv
  Sutton_link_26122024.csv
  Tower_Hamlets_link_26122024.csv
  Waltham_Forest_link_26122024.csv
  Wandsworth_link_26122024.csv
  Westminster_link_26122024.csv

In [3]:
# Merging into Single Data Frame

df = pd.concat(
    [pd.read_csv(fp) for fp in borough_files],
    ignore_index=True
)
df.head()

,priceper,year,dateoftransfer,propertytype,duration,price,postcode,lad23cd,transactionid,lmk_key,tfarea,numberrooms,classt,CURRENT_ENERGY_EFFICIENCY,POTENTIAL_ENERGY_EFFICIENCY,CONSTRUCTION_AGE_BAND
0,1115.384615,1999,1999-10-04,F,L,58000,IG11 0XN,E09000002,{C30CDD8C-3FA0-4259-ABE4-CA992C1AC593},126980681552014061013414193040742,52.0,3.0,12,78,81,England and Wales: 1991-1995
1,2942.307692,2014,2014-09-26,F,L,153000,IG11 0XN,E09000002,{10382CFD-B786-4103-A1C0-B787ED5944FB},126980681552014061013414193040742,52.0,3.0,12,78,81,England and Wales: 1991-1995
2,2644.230769,2004,2004-10-29,F,L,137500,IG11 0XN,E09000002,{8276E0B3-FDE3-41F4-8DE5-2E589472C69B},126980681552014061013414193040742,52.0,3.0,12,78,81,England and Wales: 1991-1995
3,902.884615,1997,1997-01-24,F,L,46950,IG11 0XN,E09000002,{2A289E9D-9E69-CDC8-E050-A8C063054829},126980681552014061013414193040742,52.0,3.0,12,78,81,England and Wales: 1991-1995
4,4206.349206,2023,2023-11-28,F,L,265000,IG11 7GW,E09000002,{152AB733-B73B-E651-E063-4704A8C061D9},5a6e6b6a24c2a840e15b66b8abcb70c3d09b4096b2f5e2...,63.0,3.0,12,76,79,England and Wales: 1996-2002

#### Data

In [4]:
df.shape

(2806764, 16)

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2806764 entries, 0 to 2806763
Data columns (total 16 columns):
 #   Column                       Dtype
---  ------                       -----
 0   priceper                     float64
 1   year                         int64
 2   dateoftransfer               object
 3   propertytype                 object
 4   duration                     object
 5   price                        int64
 6   postcode                     object
 7   lad23cd                      object
 8   transactionid                object
 9   lmk_key                      object
 10  tfarea                       float64
 11  numberrooms                  float64
 12  classt                       int64
 13  CURRENT_ENERGY_EFFICIENCY    int64
 14  POTENTIAL_ENERGY_EFFICIENCY  int64
 15  CONSTRUCTION_AGE_BAND        object
dtypes: float64(3), int64(5), object(8)
memory usage: 342.6+ MB

In [15]:
df.describe().round()

,priceper,year,price,tfarea,numberrooms,classt,CURRENT_ENERGY_EFFICIENCY,POTENTIAL_ENERGY_EFFICIENCY
count,2804757.0,2806764.0,2806764.0,2806764.0,2592167.0,2806764.0,2806764.0,2806764.0
mean,4360.0,2009.0,378892.0,85.0,4.0,11.0,64.0,76.0
std,3619.0,8.0,535534.0,67.0,2.0,0.0,13.0,10.0
min,0.0,1995.0,1.0,0.0,0.0,11.0,0.0,0.0
25%,2174.0,2002.0,154995.0,57.0,3.0,11.0,56.0,72.0
50%,3601.0,2008.0,255000.0,75.0,4.0,11.0,65.0,78.0
75%,5683.0,2016.0,445000.0,99.0,5.0,12.0,72.0,83.0
max,763780.0,2024.0,68250000.0,53041.0,99.0,12.0,205.0,207.0

In [9]:
# Checking Missing Values

df.isna().sum()

priceper                         2007
year                                0
dateoftransfer                      0
propertytype                        0
duration                            0
price                               0
postcode                            0
lad23cd                             0
transactionid                       0
lmk_key                             0
tfarea                              0
numberrooms                    214597
classt                              0
CURRENT_ENERGY_EFFICIENCY           0
POTENTIAL_ENERGY_EFFICIENCY         0
CONSTRUCTION_AGE_BAND           30067
dtype: int64

In [19]:
missing_count = df.isna().sum()
missing_pct = (df.isna().mean() * 100).round(2)

missing_pct

priceper                       0.07
year                           0.00
dateoftransfer                 0.00
propertytype                   0.00
duration                       0.00
price                          0.00
postcode                       0.00
lad23cd                        0.00
transactionid                  0.00
lmk_key                        0.00
tfarea                         0.00
numberrooms                    7.65
classt                         0.00
CURRENT_ENERGY_EFFICIENCY      0.00
POTENTIAL_ENERGY_EFFICIENCY    0.00
CONSTRUCTION_AGE_BAND          1.07
dtype: float64

In [20]:
# Exploring Price

df['price'].describe().apply(lambda x: f'{x:,.0f}')

count     2,806,764
mean        378,892
std         535,534
min               1
25%         154,995
50%         255,000
75%         445,000
max      68,250,000
Name: price, dtype: object

In [24]:
df

,priceper,year,dateoftransfer,propertytype,duration,price,postcode,lad23cd,transactionid,lmk_key,tfarea,numberrooms,classt,CURRENT_ENERGY_EFFICIENCY,POTENTIAL_ENERGY_EFFICIENCY,CONSTRUCTION_AGE_BAND
0,1115.384615,1999,1999-10-04,F,L,58000,IG11 0XN,E09000002,{C30CDD8C-3FA0-4259-ABE4-CA992C1AC593},126980681552014061013414193040742,52.0,3.0,12,78,81,England and Wales: 1991-1995
1,2942.307692,2014,2014-09-26,F,L,153000,IG11 0XN,E09000002,{10382CFD-B786-4103-A1C0-B787ED5944FB},126980681552014061013414193040742,52.0,3.0,12,78,81,England and Wales: 1991-1995
2,2644.230769,2004,2004-10-29,F,L,137500,IG11 0XN,E09000002,{8276E0B3-FDE3-41F4-8DE5-2E589472C69B},126980681552014061013414193040742,52.0,3.0,12,78,81,England and Wales: 1991-1995
3,902.884615,1997,1997-01-24,F,L,46950,IG11 0XN,E09000002,{2A289E9D-9E69-CDC8-E050-A8C063054829},126980681552014061013414193040742,52.0,3.0,12,78,81,England and Wales: 1991-1995
4,4206.349206,2023,2023-11-28,F,L,265000,IG11 7GW,E09000002,{152AB733-B73B-E651-E063-4704A8C061D9},5a6e6b6a24c2a840e15b66b8abcb70c3d09b4096b2f5e2...,63.0,3.0,12,76,79,England and Wales: 1996-2002
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2806759,7920.000000,2014,08/01/2014,T,F,594000,W10 4AS,E09000033,{535389DD-E9D8-4BC1-92E1-FD6D7F14E472},9.4983E+32,75.0,4.0,11,60,80,England and Wales: 1900-1929
2806760,12900.013330,2024,12/07/2024,T,F,967501,W10 4AS,E09000033,{2131FCF6-462C-86E8-E063-4804A8C0372B},9.4983E+32,75.0,4.0,11,60,80,England and Wales: 1900-1929
2806761,4055.944056,2003,30/01/2003,F,L,174000,W9 3PG,E09000033,{9E9DAC1F-D8D9-4DD2-9F35-EE3E90377051},4.10972E+32,42.9,2.0,11,80,84,England and Wales: 1930-1949
2806762,2995.337995,2001,20/07/2001,F,L,128500,W9 3PG,E09000033,{626B9E83-4BD3-420D-BCC0-627A049625E7},4.10972E+32,42.9,2.0,11,80,84,England and Wales: 1930-1949
2806763,4836.829837,2006,09/08/2006,F,L,207500,W9 3PG,E09000033,{1599790D-0B58-4080-B490-F96901B8E07B},4.10972E+32,42.9,2.0,11,80,84,England and Wales: 1930-1949