### Data Cleaning

#### Importing Libraries & Loading Data Files

In [3]:
import numpy as np
import pandas as pd
from pathlib import Path

In [4]:
project_root = Path(".").resolve().parent
raw_dir = project_root / "data" / "raw"
borough_files = sorted(raw_dir.glob("*_link_*.csv"))

df = pd.concat(
    [pd.read_csv(fp) for fp in borough_files],
    ignore_index=True,
)

#### Data

In [5]:
df.head()

,priceper,year,dateoftransfer,propertytype,duration,price,postcode,lad23cd,transactionid,lmk_key,tfarea,numberrooms,classt,CURRENT_ENERGY_EFFICIENCY,POTENTIAL_ENERGY_EFFICIENCY,CONSTRUCTION_AGE_BAND
0,1115.384615,1999,1999-10-04,F,L,58000,IG11 0XN,E09000002,{C30CDD8C-3FA0-4259-ABE4-CA992C1AC593},126980681552014061013414193040742,52.0,3.0,12,78,81,England and Wales: 1991-1995
1,2942.307692,2014,2014-09-26,F,L,153000,IG11 0XN,E09000002,{10382CFD-B786-4103-A1C0-B787ED5944FB},126980681552014061013414193040742,52.0,3.0,12,78,81,England and Wales: 1991-1995
2,2644.230769,2004,2004-10-29,F,L,137500,IG11 0XN,E09000002,{8276E0B3-FDE3-41F4-8DE5-2E589472C69B},126980681552014061013414193040742,52.0,3.0,12,78,81,England and Wales: 1991-1995
3,902.884615,1997,1997-01-24,F,L,46950,IG11 0XN,E09000002,{2A289E9D-9E69-CDC8-E050-A8C063054829},126980681552014061013414193040742,52.0,3.0,12,78,81,England and Wales: 1991-1995
4,4206.349206,2023,2023-11-28,F,L,265000,IG11 7GW,E09000002,{152AB733-B73B-E651-E063-4704A8C061D9},5a6e6b6a24c2a840e15b66b8abcb70c3d09b4096b2f5e2...,63.0,3.0,12,76,79,England and Wales: 1996-2002

In [6]:
df.shape

(2806764, 16)

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2806764 entries, 0 to 2806763
Data columns (total 16 columns):
 #   Column                       Dtype
---  ------                       -----
 0   priceper                     float64
 1   year                         int64
 2   dateoftransfer               object
 3   propertytype                 object
 4   duration                     object
 5   price                        int64
 6   postcode                     object
 7   lad23cd                      object
 8   transactionid                object
 9   lmk_key                      object
 10  tfarea                       float64
 11  numberrooms                  float64
 12  classt                       int64
 13  CURRENT_ENERGY_EFFICIENCY    int64
 14  POTENTIAL_ENERGY_EFFICIENCY  int64
 15  CONSTRUCTION_AGE_BAND        object
dtypes: float64(3), int64(5), object(8)
memory usage: 342.6+ MB

In [7]:
# Restricting to Year 2008 and onwards

df = df[df['year'] >= 2008]

In [8]:
# Keeping price range between 50k and 10M

df = df[df['price'].between(50000, 10000000)]

In [9]:
# Keeping floor area between 15 and 500 square metres

df = df[df['tfarea'].between(15, 500)]

In [10]:
# Fixing date values

df["dateoftransfer"] = pd.to_datetime(df["dateoftransfer"], format="mixed", dayfirst=True)

In [11]:
df['dateoftransfer']

1         2014-09-26
4         2023-11-28
5         2014-07-25
8         2017-06-28
9         2019-12-13
             ...
2806755   2011-11-28
2806756   2015-09-25
2806758   2017-10-27
2806759   2014-01-08
2806760   2024-07-12
Name: dateoftransfer, Length: 1411720, dtype: datetime64[ns]

In [12]:
# Resetting Index

df = df.reset_index(drop=True)

In [13]:
# Fixing Categorical Columns

df['CONSTRUCTION_AGE_BAND'] = df['CONSTRUCTION_AGE_BAND'].replace(
    ['INVALID!', 'NO DATA!'], 'unknown').fillna('unknown')

In [14]:
# Adding month column

df['month'] = df['dateoftransfer'].dt.month

In [15]:
# Adding Log Price column

df['log_price'] = np.log10(df['price'])

In [16]:
# Exploring Construction Age Band

df['CONSTRUCTION_AGE_BAND'].value_counts(ascending=False)

CONSTRUCTION_AGE_BAND
England and Wales: 1930-1949       295766
England and Wales: 1900-1929       281046
unknown                            194789
England and Wales: before 1900     164793
England and Wales: 1950-1966       119972
England and Wales: 1967-1975        78023
England and Wales: 1983-1990        56057
England and Wales: 1996-2002        48595
England and Wales: 2003-2006        43538
England and Wales: 1976-1982        37935
England and Wales: 1991-1995        29007
England and Wales: 2007 onwards     28641
England and Wales: 2007-2011         9423
2021                                 5789
2022                                 5041
England and Wales: 2012 onwards      3331
2019                                 3214
2020                                 2803
2018                                 1638
2023                                 1017
2017                                  645
2013                                  193
2016                                  166
2010                                  127
1929                                   59
2024                                   38
2014                                   20
1904                                   13
1900                                   11
2015                                   10
2012                                    7
1920                                    6
1890                                    3
1950                                    1
2000                                    1
1809                                    1
2035                                    1
Name: count, dtype: int64

In [17]:
df.head()

,priceper,year,dateoftransfer,propertytype,duration,price,postcode,lad23cd,transactionid,lmk_key,tfarea,numberrooms,classt,CURRENT_ENERGY_EFFICIENCY,POTENTIAL_ENERGY_EFFICIENCY,CONSTRUCTION_AGE_BAND,month,log_price
0,2942.307692,2014,2014-09-26,F,L,153000,IG11 0XN,E09000002,{10382CFD-B786-4103-A1C0-B787ED5944FB},126980681552014061013414193040742,52.0,3.0,12,78,81,England and Wales: 1991-1995,9,5.184691
1,4206.349206,2023,2023-11-28,F,L,265000,IG11 7GW,E09000002,{152AB733-B73B-E651-E063-4704A8C061D9},5a6e6b6a24c2a840e15b66b8abcb70c3d09b4096b2f5e2...,63.0,3.0,12,76,79,England and Wales: 1996-2002,11,5.423246
2,2906.918605,2014,2014-07-25,T,L,249995,RM9 4BT,E09000002,{8EEABC08-5995-436C-AB90-4F90CF59F029},1168092929902014070316271521540178,86.0,NaN,11,89,90,unknown,7,5.397931
3,4259.259259,2017,2017-06-28,F,L,230000,IG11 0XU,E09000002,{55BDCAE5-D63C-521D-E053-6B04A8C0DD7A},1516080632712017020216430198030049,54.0,3.0,11,80,80,England and Wales: 1996-2002,6,5.361728
4,3964.285714,2019,2019-12-13,S,F,333000,RM10 9RJ,E09000002,{9DBAD221-9A19-6EB3-E053-6B04A8C0F257},302069721132019091122222395068202,84.0,3.0,12,62,84,England and Wales: 1930-1949,12,5.522444

In [18]:
df.shape

(1411720, 18)

In [19]:
# Saving DataFrame
processed_dir = project_root /"data" /"processed"
out_path = processed_dir/'london_housing_2008_24.parquet'
df.to_parquet(out_path, index=False)