#### Feature Engineering

##### Importing Libraries and Loading Data

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from pathlib import Path

In [2]:
project_root = Path(".").resolve().parent
df = pd.read_parquet(project_root / 'data' / 'processed' / "london_housing_v2.parquet")

In [3]:
pc = pd.read_csv(project_root/'data'/'supplementary'/'london_postcodes.csv')

In [4]:
stations = pd.read_csv(project_root/'data' /'supplementary'/'tfl_stations.csv')

In [5]:
pc

,Postcode,In Use?,Latitude,Longitude,Easting,Northing,Grid Ref,County,District,Ward,...,MSOA21 Code,Middle layer super output area 2021,Census output area 2021,IMD decile,Constituency Code 2024,Constituency Name 2024,Property Type,Roads,FixPhrase,Rural/urban 2021
0,BR1 1AA,Yes,51.401545,0.015440,540293.0,168873.0,TQ402688,Greater London,Bromley,Bromley Town,...,E02000144,Bromley South,E00182600,6.0,E14001137,Bromley and Biggin Hill,Flat,Ringer's Road,cringe magnetism sardine unkempt,Urban: Nearer to a major town or city
1,BR1 1AB,Yes,51.406333,0.015234,540264.0,169405.0,TQ402694,Greater London,Bromley,Bromley Town,...,E02000134,Bromley North & Sundridge,E00003255,4.0,E14001137,Bromley and Biggin Hill,Flat,"East Street,West Street",cringe magnetism schematic udder,Urban: Nearer to a major town or city
2,BR1 1AD,No,51.400057,0.016741,540388.0,168710.0,TQ403687,Greater London,Bromley,Bromley Town,...,E02000144,Bromley South,E00182639,6.0,E14001137,Bromley and Biggin Hill,NaN,NaN,cringe magnetism sandy tightwad,Urban: Nearer to a major town or city
3,BR1 1AE,Yes,51.404543,0.014221,540199.0,169204.0,TQ401692,Greater London,Bromley,Bromley Town,...,E02000144,Bromley South,E00003266,7.0,E14001137,Bromley and Biggin Hill,Flat,Tetty Way,cringe magnetism scallop uninstall,Urban: Nearer to a major town or city
4,BR1 1AF,Yes,51.401391,0.014973,540261.0,168855.0,TQ402688,Greater London,Bromley,Bromley Town,...,E02000144,Bromley South,E00182600,6.0,E14001137,Bromley and Biggin Hill,Flat,Ringer's Road,cringe magnetism sardine undermine,Urban: Nearer to a major town or city
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
332303,WD3 8UX,Yes,51.624762,-0.494021,504345.0,192845.0,TQ043928,Greater London,Hillingdon,Harefield Village,...,E02000496,Harefield,E00012152,6.0,E14001454,"Ruislip, Northwood and Pinner",NaN,"Springwell Lane,Stockers Farm Road",crinkle magical shine vastly,Urban: Nearer to a major town or city
332304,WD3 8UZ,Yes,51.626957,-0.494122,504333.0,193089.0,TQ043930,Greater London,Hillingdon,Harefield Village,...,E02000496,Harefield,E00012152,6.0,E14001454,"Ruislip, Northwood and Pinner",Flat,Springwell Lane,crinkle magical showcase tameness,Urban: Nearer to a major town or city
332305,WD3 8XD,Yes,51.628578,-0.499183,503979.0,193262.0,TQ039932,Greater London,Hillingdon,Harefield Village,...,E02000496,Harefield,E00012152,6.0,E14001454,"Ruislip, Northwood and Pinner",NaN,"Springwell Lane,Uxbridge Road",crinkle magical showroom unopened,Urban: Nearer to a major town or city
332306,WD6 2RN,Yes,51.643273,-0.255930,520777.0,195270.0,TQ207952,Greater London,Barnet,High Barnet,...,E02000030,Totteridge & Barnet Gate,E00001422,5.0,E14001169,Chipping Barnet,Terraced,"A1,Barnet Lane",crinkle magma slimy twirl,Urban: Nearer to a major town or city
332307,WD6 2RW,Yes,51.642312,-0.256589,520734.0,195162.0,TQ207951,Greater London,Barnet,High Barnet,...,E02000030,Totteridge & Barnet Gate,E00001422,5.0,E14001169,Chipping Barnet,NaN,"A1,A5109,Barnet Lane,Barnet Road,Hyver Hill",crinkle magma slicer twice,Urban: Nearer to a major town or city

In [7]:
stations

,tfl_nlc_id,data_in_rods,name,lon,lat,remarks
0,500,1,Acton Town,-0.279917,51.502644,NaN
1,501,1,Barbican,-0.097792,51.520215,NaN
2,502,1,Aldgate,-0.075716,51.514096,NaN
3,503,1,Aldgate East,-0.071877,51.515147,NaN
4,504,0,Stratford International,-0.008861,51.545763,NaN
...,...,...,...,...,...,...
461,999961,0,Watford Vicarage Road,-0.408661,51.646792,NaN
462,999971,0,Woolwich,0.070810,51.491790,NaN
463,999990,0,Nine Elms,-0.128617,51.480154,NaN
464,999991,0,Battersea Power Station,-0.142994,51.479432,NaN
465,999999,0,Shoreditch,-0.071060,51.522600,NaN